spring.application.name=learningjwt

# Load local .env file if it exists
spring.config.import=optional:file:.env[.properties]

# MySQL DataSource
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/learningDb
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
